import fs from 'fs';
import path from 'path';

import { Injectable } from '@nestjs/common';
import { NestExpressApplication } from '@nestjs/platform-express';
import { DocumentBuilder, OpenAPIObject, SwaggerModule } from '@nestjs/swagger';

@Injectable()
export class SwaggerService {
  private staticDir = path.join(__dirname, 'static');

  setupSwagger(app: NestExpressApplication): void {
    const document = this.createDocument(app);
    SwaggerModule.setup('api', app, document, {
      customJsStr: this.loadStaticFile('swagger.custom.js'),
      customSiteTitle: 'Douglas Data Capture Platform API Docs',
      swaggerOptions: {}
    });
  }

  createDocument(app: NestExpressApplication): OpenAPIObject {
    const config = new DocumentBuilder()
      .setTitle('Douglas Data Capture Platform API')
      .setDescription('This is the autogenerated API documentation for the Douglas Data Capture Platform.')
      .setLicense('GNU Affero General Public License', 'https://www.gnu.org/licenses/agpl-3.0.txt')
      .setVersion('1.0')
      .addBearerAuth(
        {
          bearerFormat: 'JWT',
          description: 'This is a test description',
          type: 'http',
          scheme: 'bearer'
        },
        'accessToken'
      )
      .addTag('instruments')
      .addTag('users')
      .build();
    return SwaggerModule.createDocument(app, config);
  }

  private loadStaticFile(filename: string): string {
    return fs.readFileSync(path.join(this.staticDir, filename), 'utf-8');
  }
}
